### ISSUE TITLE
Kresus App fails to open on Yunohost on Raspberry pi 4 from webadmin

### ISSUE THREAD

**Issue by Didou09** [YunoHost-Apps/kresus_ynh#169]
### Describe the bug

- [x] Installed Yunohost on Raspberry Pi 4 at home => works  :+1: 

- [x] Installed Kresus on Yunohost through webadmin => installation went well :+1: 

- [ ] Cannot open the Kresus App... constantly get timeout page... :-1: 

|  clicking this |   leads to this |
|------------------|--------------------|
| ![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/016f2e81-2661-4298-a742-97674577bf73) | ![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/bd8efa3a-5a62-49c9-b881-8b6fa92203d4) |

### Context

- Hardware: *yunohost running on Raspberry Py 4 at home, accessing the raspberry server via personal PC (ubuntu) connected on same local network *
- YunoHost version: 11.2.5 (stable)
- I have access to my server: through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no, but...
  - I debugged port accessibility using the yunohost diagnostics tool
  - I managed to debunk everything (took me a full day cause I'm not an admin, first time messing with a server, learning as I do it)
  - All ports accessible, all diagnostics green except 2 things I could not debug:

|  IPv6  |  reverse DNS  |
|---------|---------------------|
| ![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/0d5143c6-3aeb-4f31-b0d2-db7668d53ec8) |![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/0606d9fb-7a93-4dde-8ac3-1a1d74ad76df) |

- Using, or trying to install package version/branch: 0.19.4~ynh4
- If upgrading, current package version: first install ever

### Steps to reproduce
see above

### Expected behavior

*A working Kresus instance, able to open normally in my browser

### Logs

I can't find any logs corresponding to the failed attempt at opening the app.

Is it possible that either the IPv6 or the reverse DNS issue is causing the app to not open ?
Please tell me it;s something else, I already struggled to make it work thus far...
I don't know how to debug these 2, and some of it depends on my Internet provider, which I have no control on, living in a shared house.

**Comment by nicofrand** [comment]
Without any logs it's hard to tell what's wrong. Maybe https://github.com/YunoHost-Apps/kresus_ynh/issues/162.

You'll have to check the apps logs, through CLI I guess.

**Comment by Didou09** [comment]
OK @nicofrand , I can connect as admin via ssh in a terminal.
Which command should I type that would be the most informative to help debug this ?

I've found this log file thus far: `/var/log/kresus/kresus.log`

It's attached too
[kresus.log](https://github.com/YunoHost-Apps/kresus_ynh/files/12923179/kresus.log)

**Comment by nicofrand** [comment]
OK, Kresus seems to be running.

What is the output of `curl http://127.0.0.1:9876 -v` ?

**Comment by Didou09** [comment]
This, does it help?

![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/7426fd72-44ae-41bf-bddb-e7b15202285f)

**Comment by nicofrand** [comment]
What about `curl http://[::1]:9876` then?

**Comment by Didou09** [comment]
This one fails:

![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/318f3efa-9532-46d0-af04-8935e2c464ed)

It's not mentionned in the Yunohost port-forwarding page:
https://yunohost.org/en/isp_box_config

What does it correspond to ? how shall I configure it ?

**Comment by nicofrand** [comment]
I just wanted to see if it was reachable through IP6.
What is the output of `netstat -plnt | grep 9876`?

**Comment by Didou09** [comment]
![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/d1d6a6a4-3e68-4005-858e-558c2b3886a4)

Does that help ?

**Comment by nicofrand** [comment]
We are now sure Kresus is running, on localhost and port 9876. It's a shame we don't see past the "LISTEN" part. I  guess it is "node"?

That also means the `curl http://127.0.0.1:9876` should work. Can you try again? You are doing it from the raspberry right?
What about `nc -zv 127.0.0.1 9876`?

**Comment by Didou09** [comment]
So I'm doing everything from the raspberry (I connect to it via ssh from my pc).

There was nothing after the "LISTEN" in the previous screenshot, I've done it again below:
![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/d0a953ce-8715-472b-9e78-cbe0af018439)

In that test I had to interrupt the `curl http://127.0.0.1:9876` because nothing was happening (I waited ~30 seconds). This particular command does not seem to work.

**Comment by nicofrand** [comment]
Ah, can you try running the `netstat` command as sudo please?

That should look like this:

```tcp        0      0 127.0.0.1:33060         0.0.0.0:*               LISTEN      1365/mysqld  
```

**Comment by Didou09** [comment]
It's indeed listening to something:

![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/0061bdf7-47e9-4612-8b1c-fa8247df10ac)

**Comment by Didou09** [comment]
@nicofrand any chance there is a solution to this ?

**Comment by nicofrand** [comment]
Does it occur every time you try to install it? As far as I can tell from the logs, Kresus in running alright. The issue comes from your network I guess but I don't know what is going on…
You might want to try to get some help on the Yunohost room on Matrix, or on the forum.

**Comment by Didou09** [comment]
So I tried uninstalling and re-installing => same behaviour.

Like you suggested @nicofrand, I understand this may to do with how my network and / or yunohost is configured.
I tried reaching out to the yunohost folks both on the Matrix chatroom and on the [forum](https://forum.yunohost.org/t/app-is-installed-and-runs-but-timesout/26927).
It's been 22 days now and I haven't received a single answer, I'm not even sure anyone has actually looked at the messages.
I think I'll give up,  I'm stuck and don't know how to solve the probem.

Do you know any other good open source client-side app for personal finance that does not require to run on a server ?
Thanks for your help,

**Comment by Didou09** [comment]
ok, looks like someone (you?) just answered on Matrix after I re-posted the same message again, thanks

**Comment by nicofrand** [comment]
Yup, it was me.
Can you try `curl -4 http://127.0.0.1:9876`?
And `service kresus status`?

**Comment by Didou09** [comment]
done, posted on Matrix, 

Thanks for your help ! very appreciated

**Comment by nicofrand** [comment]
Answers from Matrix:

* `curl -4 http://127.0.0.1:47603` (port has changed meanwhile) hangs as well
* `curl http://[::1]:47603` returns "connection refused"
* `service kresus status` is OK

I still don't know why the request times out.

**Comment by nicofrand** [comment]
Can you try `curl http://127.0.0.1:47603/kresus` please?
Also the content of `/etc/nginx/conf.d/warren.nohost.me.d/kresus.conf` (or something like that).

**Comment by bnjbvr** [comment]
Do you have set a firewall?

**Comment by Didou09** [comment]
curl http://127.0.0.1:47603/kresus

![image](https://github.com/YunoHost-Apps/kresus_ynh/assets/5929562/48e5a6ef-0182-4208-9422-824446c46f1c)

**Comment by Didou09** [comment]
content of `/etc/nginx/conf.d/warren.nohost.me.d/kresus.conf`

```
 rewrite ^/kresus$ /kresus/ permanent;
location /kresus/ {
  alias /var/www/kresus/build/client/;
  try_files $uri $uri/index.html @kresus;

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}

location ~ /kresus/\.(css|js|png|jpe?g|svg|eot|woff2?)$ {
  more_set_headers 'Cache-Control: max-age=2592000, must-revalidate, public';
  gzip_types text/plain text/css application/javascript text/javascript;
  try_files $uri $uri/index.html @kresus;
}

location @kresus {
  client_max_body_size  8M;
  send_timeout          600;
  proxy_connect_timeout 600;
  proxy_send_timeout    600;
  proxy_read_timeout    600;
  proxy_set_header      Host $host;

  proxy_pass http://127.0.0.1:47603;
  proxy_redirect off;
}

```

**Comment by Didou09** [comment]
> Do you have set a firewall?

Not sure actually.
I did not install one myself, that's for sure.
Maybe my Internet Service Provider (ISP) implements one in the router by default ?
I'm living in the USA since 4 month, not sure what the habits are here, I'll ask some colleagues

**Comment by Didou09** [comment]
Also here the logs from the diagnostics (someone asked for it on Matrix):

[https://paste.yunohost.org/raw/ociyonizup](https://paste.yunohost.org/raw/ociyonizup)

**Comment by nicofrand** [comment]
OK, I think I see what's going on and it has nothing to do with this package nor Kresus.

How do you access your YunoHost admin?
Please try accessing https://warren.nohost.me from a different network.
If that works please take a look at https://yunohost.org/en/dns_local_network.

**Comment by Didou09** [comment]
OK, thanks

* I tried accessing it via my mobile phone using the 4G network => it worked
* Hence it does not work only when I try to access it via my local PC which is on the same local domestic network (router) as the raspberry pi
* My ISP does not seem to allow me to implement a custom domain name in the DNS (or I don't understand how to do it)
* But I could modify my /etc/hosts file to include the local IP vs domain correspondence => it works now :+1: 

Now I can access Kresus and try to create a first account / connection to my bank
Thanks a lot

I have a new question directly concerning Kresus:
I see that to create a direct connection to my bank I nee to give my login and password.
How are these credentials saved in Kresus ? Are they crypted ? how can I be sure they are not saved in plain text ?

Also, is there an option to manually enter them everytime I want to update / download data from the bank instead of storing them permanently ?

**Comment by nicofrand** [comment]
OK, I'll close this issue then.

For any question directly related to Kresus please refer to the FAQ (https://kresus.org/en/faq.html#how-is-my-banking-data-stored-in-kresus) or the forum (https://community.kresus.org).

You can also see open issues/feature requests on Kresus' repository: https://framagit.org/kresusapp/kresus/.
